# Generated by Django 4.2.11 on 2024-10-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktails',
            fields=[
                ('drinkID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('glass', models.CharField(blank=True, max_length=200, null=True)),
                ('instructions', models.TextField()),
                ('thumbnail', models.URLField()),
                ('ingredients', models.JSONField(blank=True, null=True)),
                ('measurements', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
