# Generated by Django 4.2.11 on 2024-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('mealID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('instructions', models.TextField()),
                ('thumbnail', models.URLField()),
                ('ingredients', models.JSONField(blank=True, null=True)),
                ('measurements', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewID',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_meals',
            field=models.ManyToManyField(blank=True, to='ourapp.meals'),
        ),
    ]
