# Generated by Django 4.2.11 on 2024-10-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0005_mealreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='reccomended_pairing',
            field=models.TextField(null=True),
        ),
    ]
